[package]
name = "reed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.7.5"
pest_derive = "2.7.5"
clap = { version = "4.4.8", features= ["derive"], optional = true }
lalrpop-util = {version = "0.20.0", features = ["lexer", "unicode"] }

[build-dependencies]
lalrpop = "0.20.0"

[features]
cli = ["clap"]

[[bin]]
name = "reedi"
required-features = ["cli"]