/// The Concrete Syntax Tree (Parse Tree) is a literal representation of the parsed string.
/// The structure is generated by the parser generator (pest).
use pest::{error::Error, iterators::Pairs, Parser};

#[derive(pest_derive::Parser)]
#[grammar = "src/parser/grammar.pest"]
pub struct CstParser;

// clippy complains the the pest error type is too large to return without boxing it.
// We don't have control of that though, since pest::Parser::parse returns the unboxed error.
#[allow(clippy::result_large_err)]
pub fn cst_parse(input: &str) -> Result<Pairs<'_, Rule>, Error<Rule>> {
    // clippy: disable
    CstParser::parse(Rule::program, input)
}
