/// The Concrete Syntax Tree (Parse Tree) is a literal representation of the parsed string.
/// The structure is generated by the parser generator (pest).
use pest::{error::Error, iterators::Pairs, Parser};

#[derive(pest_derive::Parser)]
#[grammar = "src/parser/grammar.pest"]
pub struct CstParser;

pub fn cst_parse<'i>(input: &'i str) -> Result<Pairs<'i, Rule>, Error<Rule>> {
    CstParser::parse(Rule::program, input)
}
